# Generated by Django 4.1.3 on 2022-12-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nagłówek')),
                ('preview', models.CharField(max_length=250, verbose_name='Ogłoszenie')),
                ('full_text', models.TextField(verbose_name='Artykuł')),
                ('date', models.DateTimeField(verbose_name='Data publikacji')),
            ],
        ),
    ]
